name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t harcgameweb .

    - name: Run tests
      run: docker run --rm harcgameweb sh -c "make migrate && make test"
